//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;
using System.Xml.Serialization;
using System.Runtime.Serialization;
namespace Models2
{
    





[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Container", Namespace = "")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AxleContainer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BinaryContainer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VehicleContainer))]
    public class Container : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private ulong IDField;

        private BGuid CreatedByField;

        private System.DateTime CreatedField;

        private ArrayOfString CaptionsField;

        private ContainerExtension[] ExtensionsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public ulong ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        [XmlElement()]
        public BGuid CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement("Created", DataType = "date", Type = typeof(DateTime))]
        public System.DateTime Created
        {
            get
            {
                return this.CreatedField;
            }
            set
            {
                this.CreatedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public ArrayOfString Captions
        {
            get
            {
                return this.CaptionsField;
            }
            set
            {
                this.CaptionsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public ContainerExtension[] Extensions
        {
            get
            {
                return this.ExtensionsField;
            }
            set
            {
                this.ExtensionsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BGuid", Namespace = "")]
    public class BGuid : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private uint PlatformIdField;

        private ushort BGuidTypeField;

        private ushort KeyMarkField;

        private ulong IDField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public uint PlatformId
        {
            get
            {
                return this.PlatformIdField;
            }
            set
            {
                this.PlatformIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public ushort BGuidType
        {
            get
            {
                return this.BGuidTypeField;
            }
            set
            {
                this.BGuidTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public ushort KeyMark
        {
            get
            {
                return this.KeyMarkField;
            }
            set
            {
                this.KeyMarkField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public ulong ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AxleContainer", Namespace = "")]
    [Serializable()]
    [XmlType(AnonymousType = true, Namespace = "")]
    public class AxleContainer : Container
    {

        private int IndexField;

        private int UnitField;

        private int GroupField;

        private int PositionField;

        private int WeightField;

        private int WeightLeftField;

        private int WeightRightField;

        private int WeightLimitField;

        private int WheelCountField;

        private int FootprintWidthLeftField;

        private int FootprintWidthRightField;

        private bool IsOverweightField;

        private double SpeedField;

        private int CredenceField;

        private AxleMeasurementStatus MeasurementStatusField;

        private byte[] WheelPairingField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Index
        {
            get
            {
                return this.IndexField;
            }
            set
            {
                this.IndexField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Unit
        {
            get
            {
                return this.UnitField;
            }
            set
            {
                this.UnitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int WeightLeft
        {
            get
            {
                return this.WeightLeftField;
            }
            set
            {
                this.WeightLeftField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int WeightRight
        {
            get
            {
                return this.WeightRightField;
            }
            set
            {
                this.WeightRightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int WeightLimit
        {
            get
            {
                return this.WeightLimitField;
            }
            set
            {
                this.WeightLimitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int WheelCount
        {
            get
            {
                return this.WheelCountField;
            }
            set
            {
                this.WheelCountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int FootprintWidthLeft
        {
            get
            {
                return this.FootprintWidthLeftField;
            }
            set
            {
                this.FootprintWidthLeftField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int FootprintWidthRight
        {
            get
            {
                return this.FootprintWidthRightField;
            }
            set
            {
                this.FootprintWidthRightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool IsOverweight
        {
            get
            {
                return this.IsOverweightField;
            }
            set
            {
                this.IsOverweightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public double Speed
        {
            get
            {
                return this.SpeedField;
            }
            set
            {
                this.SpeedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Credence
        {
            get
            {
                return this.CredenceField;
            }
            set
            {
                this.CredenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public AxleMeasurementStatus MeasurementStatus
        {
            get
            {
                return this.MeasurementStatusField;
            }
            set
            {
                this.MeasurementStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public byte[] WheelPairing
        {
            get
            {
                return this.WheelPairingField;
            }
            set
            {
                this.WheelPairingField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BinaryContainer", Namespace = "")]
    [Serializable()]
    [XmlType(AnonymousType = true, Namespace = "")]
    public partial class BinaryContainer : Container
    {

        private BinaryContainerType BinaryTypeField;

        private string NameField;

        private ulong LengthField;

        private byte[] DataField;

        private byte[] HashField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public BinaryContainerType BinaryType
        {
            get
            {
                return this.BinaryTypeField;
            }
            set
            {
                this.BinaryTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public ulong Length
        {
            get
            {
                return this.LengthField;
            }
            set
            {
                this.LengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string Data
        {
            get
            {
                return System.Text.Encoding.UTF8.GetString(this.DataField);
            }
            set
            {
                this.DataField = System.Text.Encoding.UTF8.GetBytes(value);
            }

        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string Hash
        {
            get
            {
                return System.Text.Encoding.UTF8.GetString(this.HashField);
            }
            set
            {
                this.HashField = System.Text.Encoding.UTF8.GetBytes(value);
            }
        }
    }

    [System.Runtime.Serialization.DataContractAttribute(Name = "VehicleContainer", Namespace = "")]
    [Serializable()]
    
    [XmlRoot("VehicleContainer", Namespace = "")]
    public class VehicleContainer : Container
    {

        private BinaryContainer[] BinariesField;

        private int ChannelNumberField;

        private int LaneNumberField;

        private Direction DirectionField;

        private int CredenceField;

        private bool CredenceExceededField;

        private TimeSpan HeadingField;

        private TimeSpan GapField;

        private double SpeedField;

        private double SpeedDifferenceField;

        private int LengthField;

        private int WidthField;

        private int HeightField;

        private int PositionLeftField;

        private int PositionRightField;

        private Classification[] ClassificationField;

        private string VehicleTypeNameField;

        private int UnitsField;

        private int WheelBaseField;

        private int WeightField;

        private int WeightLimitField;

        private int OverweightField;

        private int AxleCountField;

        private AxleContainer[] AxlesField;

        private string PlateField;

        private double PlateConfidenceField;

        private System.Nullable<bool> PlateValidField;

        private string PlateRearField;

        private double PlateRearConfidenceField;

        private System.Nullable<bool> PlateRearValidField;

        private string CountryCodeField;

        private string CountrySubdivisionCodeField;

        private double CountryConfidenceField;

        private bool AdrFrontEmptyField;

        private string AdrFrontKemlerField;

        private string AdrFrontUnField;

        private double AdrFrontConfidenceField;

        private bool AdrRearEmptyField;

        private string AdrRearKemlerField;

        private string AdrRearUnField;

        private double AdrRearConfidenceField;

        private bool IsOverweightPartialField;

        private bool IsOverweightGrossField;

        private bool IsExceededLengthField;

        private bool IsExceededWidthField;

        private bool IsExceededHeightField;

        private bool IsOverspeedField;

        private bool IsWrongDirectionField;

        private bool IsNonStandardField;

        private bool OperatingRangeExceededSpeedField;

        private bool OperatingRangeExceededWeightField;

        private bool DivertField;

        private bool DivertedField;

        private ulong ChecksumField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlArray("Binaries")]
        [XmlArrayItem("BinaryContainer")]
        public BinaryContainer[] Binaries
        {
            get
            {
                return this.BinariesField;
            }
            set
            {
                this.BinariesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int ChannelNumber
        {
            get
            {
                return this.ChannelNumberField;
            }
            set
            {
                this.ChannelNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int LaneNumber
        {
            get
            {
                return this.LaneNumberField;
            }
            set
            {
                this.LaneNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public Direction Direction
        {
            get
            {
                return this.DirectionField;
            }
            set
            {
                this.DirectionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Credence
        {
            get
            {
                return this.CredenceField;
            }
            set
            {
                this.CredenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool CredenceExceeded
        {
            get
            {
                return this.CredenceExceededField;
            }
            set
            {
                this.CredenceExceededField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        [XmlElement()]
        public TimeSpan Heading
        {
            get
            {
                return this.HeadingField;
            }
            set
            {
                this.HeadingField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        [XmlElement()]
        public TimeSpan Gap
        {
            get
            {
                return this.GapField;
            }
            set
            {
                this.GapField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public double Speed
        {
            get
            {
                return this.SpeedField;
            }
            set
            {
                this.SpeedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public double SpeedDifference
        {
            get
            {
                return this.SpeedDifferenceField;
            }
            set
            {
                this.SpeedDifferenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Length
        {
            get
            {
                return this.LengthField;
            }
            set
            {
                this.LengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int PositionLeft
        {
            get
            {
                return this.PositionLeftField;
            }
            set
            {
                this.PositionLeftField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int PositionRight
        {
            get
            {
                return this.PositionRightField;
            }
            set
            {
                this.PositionRightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlArray("Classification")]
        [XmlArrayItem("Classification")]
        public Classification[] Classification
        {
            get
            {
                return this.ClassificationField;
            }
            set
            {
                this.ClassificationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string VehicleTypeName
        {
            get
            {
                return this.VehicleTypeNameField;
            }
            set
            {
                this.VehicleTypeNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Units
        {
            get
            {
                return this.UnitsField;
            }
            set
            {
                this.UnitsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int WheelBase
        {
            get
            {
                return this.WheelBaseField;
            }
            set
            {
                this.WheelBaseField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int WeightLimit
        {
            get
            {
                return this.WeightLimitField;
            }
            set
            {
                this.WeightLimitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Overweight
        {
            get
            {
                return this.OverweightField;
            }
            set
            {
                this.OverweightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int AxleCount
        {
            get
            {
                return this.AxleCountField;
            }
            set
            {
                this.AxleCountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlArray("Axles")]
        [XmlArrayItem("AxleContainer")]
        public AxleContainer[] Axles
        {
            get
            {
                return this.AxlesField;
            }
            set
            {
                this.AxlesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string Plate
        {
            get
            {
                return this.PlateField;
            }
            set
            {
                this.PlateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public double PlateConfidence
        {
            get
            {
                return this.PlateConfidenceField;
            }
            set
            {
                this.PlateConfidenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public System.Nullable<bool> PlateValid
        {
            get
            {
                return this.PlateValidField;
            }
            set
            {
                this.PlateValidField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string PlateRear
        {
            get
            {
                return this.PlateRearField;
            }
            set
            {
                this.PlateRearField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public double PlateRearConfidence
        {
            get
            {
                return this.PlateRearConfidenceField;
            }
            set
            {
                this.PlateRearConfidenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public System.Nullable<bool> PlateRearValid
        {
            get
            {
                return this.PlateRearValidField;
            }
            set
            {
                this.PlateRearValidField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string CountrySubdivisionCode
        {
            get
            {
                return this.CountrySubdivisionCodeField;
            }
            set
            {
                this.CountrySubdivisionCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public double CountryConfidence
        {
            get
            {
                return this.CountryConfidenceField;
            }
            set
            {
                this.CountryConfidenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool AdrFrontEmpty
        {
            get
            {
                return this.AdrFrontEmptyField;
            }
            set
            {
                this.AdrFrontEmptyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string AdrFrontKemler
        {
            get
            {
                return this.AdrFrontKemlerField;
            }
            set
            {
                this.AdrFrontKemlerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string AdrFrontUn
        {
            get
            {
                return this.AdrFrontUnField;
            }
            set
            {
                this.AdrFrontUnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public double AdrFrontConfidence
        {
            get
            {
                return this.AdrFrontConfidenceField;
            }
            set
            {
                this.AdrFrontConfidenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool AdrRearEmpty
        {
            get
            {
                return this.AdrRearEmptyField;
            }
            set
            {
                this.AdrRearEmptyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string AdrRearKemler
        {
            get
            {
                return this.AdrRearKemlerField;
            }
            set
            {
                this.AdrRearKemlerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string AdrRearUn
        {
            get
            {
                return this.AdrRearUnField;
            }
            set
            {
                this.AdrRearUnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public double AdrRearConfidence
        {
            get
            {
                return this.AdrRearConfidenceField;
            }
            set
            {
                this.AdrRearConfidenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool IsOverweightPartial
        {
            get
            {
                return this.IsOverweightPartialField;
            }
            set
            {
                this.IsOverweightPartialField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool IsOverweightGross
        {
            get
            {
                return this.IsOverweightGrossField;
            }
            set
            {
                this.IsOverweightGrossField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool IsExceededLength
        {
            get
            {
                return this.IsExceededLengthField;
            }
            set
            {
                this.IsExceededLengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool IsExceededWidth
        {
            get
            {
                return this.IsExceededWidthField;
            }
            set
            {
                this.IsExceededWidthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool IsExceededHeight
        {
            get
            {
                return this.IsExceededHeightField;
            }
            set
            {
                this.IsExceededHeightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool IsOverspeed
        {
            get
            {
                return this.IsOverspeedField;
            }
            set
            {
                this.IsOverspeedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool IsWrongDirection
        {
            get
            {
                return this.IsWrongDirectionField;
            }
            set
            {
                this.IsWrongDirectionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool IsNonStandard
        {
            get
            {
                return this.IsNonStandardField;
            }
            set
            {
                this.IsNonStandardField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool OperatingRangeExceededSpeed
        {
            get
            {
                return this.OperatingRangeExceededSpeedField;
            }
            set
            {
                this.OperatingRangeExceededSpeedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool OperatingRangeExceededWeight
        {
            get
            {
                return this.OperatingRangeExceededWeightField;
            }
            set
            {
                this.OperatingRangeExceededWeightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool Divert
        {
            get
            {
                return this.DivertField;
            }
            set
            {
                this.DivertField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public bool Diverted
        {
            get
            {
                return this.DivertedField;
            }
            set
            {
                this.DivertedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public ulong Checksum
        {
            get
            {
                return this.ChecksumField;
            }
            set
            {
                this.ChecksumField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfString", Namespace = "", ItemName = "string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ContainerExtension", Namespace = "")]
    public class ContainerExtension : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string NameField;

        private Container ContainerField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public Container Container
        {
            get
            {
                return this.ContainerField;
            }
            set
            {
                this.ContainerField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TimeSpan", Namespace = "")]
    public class TimeSpan : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Direction", Namespace = "")]
    public enum Direction : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "Unknown")]
        Unknown = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "Ahead")]
        Ahead = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "Back")]
        Back = 2,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Classification", Namespace = "")]
    public  class Classification : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string SchemaField;

        private int IndexField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        [XmlElement()]
        public string Schema
        {
            get
            {
                return this.SchemaField;
            }
            set
            {
                this.SchemaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [XmlElement()]
        public int Index
        {
            get
            {
                return this.IndexField;
            }
            set
            {
                this.IndexField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AxleMeasurementStatus", Namespace = "")]
    public enum AxleMeasurementStatus : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "Unknown")]
        Unknown = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "Correct")]
        Correct = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "WeightLimitUnder")]
        WeightLimitUnder = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "WeightLimitOver")]
        WeightLimitOver = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "SpeedLimitUnder")]
        SpeedLimitUnder = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "SpeedLimitOver")]
        SpeedLimitOver = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "Error")]
        Error = 6,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BinaryContainerType", Namespace = "")]
    public enum BinaryContainerType : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "Unknown")]
        Unknown = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "ImageBmp")]
        ImageBmp = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "ImageEmf")]
        ImageEmf = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "ImageExif")]
        ImageExif = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "ImageGif")]
        ImageGif = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "ImageIcon")]
        ImageIcon = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "ImageJpeg")]
        ImageJpeg = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "ImageMemoryBmp")]
        ImageMemoryBmp = 7,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "ImagePng")]
        ImagePng = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "ImageTiff")]
        ImageTiff = 9,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "ImageWmf")]
        ImageWmf = 10,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "VideoAvi")]
        VideoAvi = 11,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "VideoWebm")]
        VideoWebm = 12,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "VideoMkv")]
        VideoMkv = 13,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [XmlEnum(Name = "VideoMp4")]
        VideoMp4 = 14,
    }
}